baseURL = 'https://saurabblog.vercel.app/'
languageCode = 'en-us'
title = 'Saurab Blog'

paginate = 4
[params]
    description = "Blog website maintained by Saurab Poudel"
    dateFormat = "Jan 2,2006"

[taxonomies]
    category = "categories"
    author = "authors"